steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker build -t us-east4-docker.pkg.dev/$PROJECT_ID/backend-image:tag1 .
  automapSubstitutions: true
images:
- 'us-east4-docker.pkg.dev/$PROJECT_ID/backend/backend-image:tag1'
